name: mlhub
channels:
  - conda-forge
dependencies:
  - python=3.7
  - boto3
  - jupyter
  - requests
  - xarray
  - rasterio  # to read tif and jp2 files
  - black  # formatting
  - mypy  # type checking
  - pandas
